### ISSUE TITLE
not sure how to use it my own dataset

### ISSUE THREAD

**Issue by ron-weiner** [philipperemy/tensorflow-phased-lstm#8]
Hey,
I'm not sure about the shppe of the used data from mnist in your code.

I have 9 different sensors which simultaneously record for 3072 time steps, at the end of that record i have 3 possible classes.

it means:
- x values are 9x3072
- y values 1x3

I wish to use your code in order to give a prediction for what is the right class.

I'm sure it is a minor change but i'm struggling  /=

What do you think?

Thanks

**Comment by philipperemy** [comment]
Ok it should not be difficult for you.

From this script: https://github.com/philipperemy/tensorflow-phased-lstm/blob/master/official_tensorflow_phased_lstm.py

```
x_ = tf.placeholder(tf.float32, (batch_size, mnist_img_size, 1))
t_ = tf.placeholder(tf.float32, (batch_size, mnist_img_size, 1))
y_ = tf.placeholder(tf.float32, (batch_size, num_classes))
```

In your case `mnist_img_size=3072`. That's the length of your sequence.

Your input x has 9 inputs per time step. So you should use a 9 instead of a 1.

num_classes=3 in your case.

For batch_size you can use any possible value. If you don't know what to use, just set it to 1 and increase it later.

Your input should like like:
```
x_ = tf.placeholder(tf.float32, (1, 3072, 9))
t_ = tf.placeholder(tf.float32, (1, 3072, 9))
y_ = tf.placeholder(tf.float32, (1, 3))
```

Then your t are the timestamps of the recordings. If you save the timestep every 60 seconds (synchronous) for example, just feed range(3072) per sensor (just make range(3072) and duplicate it 9 times to match the input tensor shape 1-3072-9) to the tensorflow.session.

If the inputs arrive at irregular time intervals, input the raw timestamps to the tensorflow session.

**Comment by ron-weiner** [comment]
Thank you very much @philipperemy 
I will try it this week and will let you know!

**Comment by philipperemy** [comment]
Great! I’m closing this issue now! Feel free to re open it :)
